#########
# Paths #
#########
raw_stix_bundles_path: /mnt/data/openCTI/data/bundles/raw # Read path
processed_stix_bundles_path: /mnt/data/openCTI/data/bundles/processed # Save path

##########################
# Training Dataset Paths #
##########################
training_examples_file: /mnt/data/openCTI/data/training_examples.txt
input_path: /mnt/data/openCTI/bundles/processed/complete_bundles
output_path: /mnt/data/openCTI/data/reports/final-reports
io_save_path: /mnt/data/openCTI/data/io-pairs-ids-unchanged

##################################################
# Drop any SDO that is not needed in STIX bundle #
##################################################
stix_objects_to_ignore: 
  marking-definition: []
  identity:
    - [name, AlienVault]

##########################################
# Replace UUIDs with new custom made ids #
##########################################
replace_ids: False

####################################################
# Split data in Domain Objects while saving.       #
# STIX bundles will contain only the selected type #
# of SDO or SCO or SRO. ONLY one Object type       #
# will be present in STIX bundles                  #
####################################################
split_stix_types_in_saving:
  - identity
  - report
  - relationship
  - indicator
  - file
  - malware 
  - attack-pattern 
  - domain-name
  - intrusion-set 
  - url
  - vulnerability 
  - location
  - hostname
  - cryptocurrency-wallet 
  - email-addr
  - ipv4-addr